// import "./assets/js/vendor/modernizr-2.8.3.min.js";
import "./assets/js/vendor/jquery-1.12.4.min.js";
// import "./assets/js/vendor/popper.min.js";
// import "./assets/js/bootstrap.min.js";
import "./assets/js/ajax-mail.js";
import "./assets/js/jquery.meanmenu.min.js";
// import "./assets/js/wow.min.js";
import "./assets/js/slick.min.js";
import "./assets/js/owl.carousel.min.js";
import "./assets/js/jquery.magnific-popup.min.js";
import "./assets/js/isotope.pkgd.min.js";
import "./assets/js/imagesloaded.pkgd.min.js";
import "./assets/js/jquery.mixitup.min.js";
import "./assets/js/jquery.countdown.min.js";
import "./assets/js/jquery.counterup.min.js";
// import "./assets/js/waypoints.min.js";
import "./assets/js/jquery.barrating.min.js";
import "./assets/js/jquery-ui.min.js";
import "./assets/js/venobox.min.js";
import "./assets/js/jquery.nice-select.min.js";
import "./assets/js/scrollUp.min.js";
// import "./assets/js/main.js";